### ISSUE TITLE
Make juicer work with REI

### ISSUE THREAD

**Issue by ITotallyExist** [ITotallyExist/Melon-slabs#1]
make it so the model shows if there js a bottle in it and if there is fruits/cactus in it.

add recipes for melon juice, apple juice, cactus juice, frankenmelon juice.

melon and apple just take two or three and peovide more food.  cactus fucks you up, frankenmelon for the magic ingredient in the magic mod.

**Comment by ITotallyExist** [comment]
juice and apple and melon and golden apple juices all added, just cactus juice.  frankenmelon juice will be in weather addon mod

**Comment by ardissaps** [comment]
also please support REI recipe for juicer items

**Comment by ITotallyExist** [comment]
Working on this now
